### ISSUE TITLE
Link to posts in the menu

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/bloccit#1]
Hi,

I am a user of your application since day 1, and I've been enjoying the ride so far. Thx!

One problem that I have though, is that I need to manually type the full URL to access the posts list. I'd rather click on a button in the top navigation.

Would you consider adding a link to the posts?

Should be a piece of :cake: for you!

**Comment by chikamichi** [comment]
@UJKhokhar you never answered me :cry:

**Comment by chikamichi** [comment]
I guess it should be a link to the topics list now, though.

**Comment by UJKhokhar** [comment]
Sorry! I was supposed to ask you about that. Topics link makes sense. I'll
add that next.

**Comment by chikamichi** [comment]
Don't forget to close issues once solved/fixed/discared.
