### ISSUE TITLE
Style checking?

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/bloccit#12]
Hey,

I noticed in a few files that you have trailing spaces, that is, extra, useless spaces at the end of some lines.

My editor for instance displays those in red, and I can quickly delete them all using a vi command. But trailing spaces is just an aspect of a more general concern, that is styling. Indentation, naming conventions, spacing etc.

You may be interested in [Hound](https://houndci.com), which provides syntax-checking as a service for free for public GitHub projects. I never used it (it's kind of new), but we could try it!

**Comment by chikamichi** [comment]
It works by reviewing pull requests, so using topic-branches and pull requests would be the way to go in that perspective (meaning, you would edit the `master` branch *only* by merging pull requests from topic branches, which is a nice workflow actually, even when working on your own).

**Comment by UJKhokhar** [comment]
Okay so I'll create push topic branches and create pull requests. I'll also see if there is a sublime plugin for spacing.

**Comment by chikamichi** [comment]
@UJKhokhar I'm closing this issue, I have too many open and that one is not relevant anymore :)
