### ISSUE TITLE
Upvote and downvote values are two.

### ISSUE THREAD

**Issue by UJKhokhar** [UJKhokhar/bloccit#7]
Tested on local. When user upvotes post, total votes for post increase by two. When user downvotes, total votes decreases by two.

**Comment by chikamichi** [comment]
Is that a bug in your current implementation? I am not sure :)

**Comment by UJKhokhar** [comment]
I don't think it's error actually. Posts have 1 upvote by default. If you as a user upvotes, then total points is 2. If you as the same user then downvote, the post has 1 upvote and 1 downvote totaling to 0.

tl:dr I forgot how to math.
